---
language: [ ruby, node_js ]
rvm: [ 2.2.0 ]
node_js: [ 0.10 ]
cache: bundler
sudo: false

before_script:
  - npm install bower -g
  - bower install

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

# Set the branch that will be built and published to GitHub pages.
branches:
  only:
    - demo

# Create a GitHub Personal Access Token.
# Install the travis gem.
# Run the command below (fill in your name, email, and token):
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com GH_TOKEN=token'
# Replace the value of secure with your generated value.
env:
  - secure: "QNCaknbp2d0dmgTJnDK4YXjlsY1V2iNbAh7kzSZLsXH8Nl9BnD7j73dYb2nDYwyXH30ZZm4I9TyZouH/mM3IvnIeYerV1s/uQP5VaPAondSTSv7iIxSuArhyTY+vl2Kmzw6eomNw44/0hPLJxWnwsv58Jxhtb3gQ8cCPCwuqeJk="
