---
language: [ ruby, node_js ]
rvm: [ 2.2.1 ]
node_js: [ 0.12 ]
cache:
  bundler: true
  directories:
    - bower_components
sudo: false

before_script:
  - npm install -g bower
  - bower install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the first command below with the generated one.
before_install:
  - openssl aes-256-cbc -K $encrypted_3078eeabf3e7_key -iv $encrypted_3078eeabf3e7_iv -in .deploy_key.enc -out .deploy_key -d
  - eval "$(ssh-agent)"
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

# Set the branch that will be built and published to GitHub pages.
branches:
  only:
    - demo

# Run the command below (fill in your name and email):
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com'
# Replace the value of secure with your generated value.
env:
  - secure: "ZsXjYKbT1DET7wTVJRWNP0Ms2P1QiVsDT+gqsTKLI/k2y3c9I2l138yr31RGB0rdEhkLgSYqd1KwxoNsubMdsEcGZiReI6/uCliDSTWf2JTy0tUiVDhwB2YGBz8PkiB2oR+TWDRHtn16qv0bFkQ7xoEskTUrb6KWW4wOiVGkDGk="
