---
language: [ ruby, node_js ]
rvm: [ 2.2.2 ]
node_js: [ iojs ]
cache:
  bundler: true
  directories:
    - bower_components
sudo: false

before_script:
  - npm install -g bower
  - bower install

# Install the travis gem.
# Create a deploy key and encrypt it with:
# $ travis encrypt-file .deploy_key
# Commit the encrypted file and
# replace the first command below with the generated one.
before_install:
  - openssl aes-256-cbc -K $encrypted_3078eeabf3e7_key -iv $encrypted_3078eeabf3e7_iv -in .deploy_key.enc -out .deploy_key -d
  - eval "$(ssh-agent)"
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis

# Run the command below (fill in your name and email):
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com'
# Replace the value of secure with your generated value.
env:
  - secure: "Tlv6KPbkXe+hw98RuxD4gHwT6WLpirqlaFl6jUI/N/XnqANLVAEfzTlncUc3pd8R1yE/I+oRvQFacpO92f6K/Evu1ZK3/Ehyia8dK8WBo384R1c8XmWJBK78Ei4fnZt28u1wdeg0TF0a6yPhKlqATShRitrINPfGsL6jca+vROk="
